// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client'

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

/**
 * Content for Author documents
 */
interface AuthorDocumentData {
  /**
   * Image field in *Author*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: author.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * Name field in *Author*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: author.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField
}

/**
 * Author document from Prismic
 *
 * - **API ID**: `author`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AuthorDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<AuthorDocumentData>, 'author', Lang>

type BuildPageDocumentDataSlicesSlice =
  | PageBannerSlice
  | LogosSlice
  | MeetTheTeamSlice
  | TestimonialsSlice
  | ImageSlice
  | FeatureGridSlice
  | SectionIntroSlice

/**
 * Content for Build Page documents
 */
interface BuildPageDocumentData {
  /**
   * Slice Zone field in *Build Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: build_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BuildPageDocumentDataSlicesSlice> /**
   * Meta Title field in *Build Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: build_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField

  /**
   * Meta Description field in *Build Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: build_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Build Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: build_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>
}

/**
 * Build Page document from Prismic
 *
 * - **API ID**: `build_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BuildPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<BuildPageDocumentData>,
    'build_page',
    Lang
  >

type BuyPageDocumentDataSlicesSlice = TipSlice | TextSlice | PageBannerSlice

/**
 * Content for Buy Page documents
 */
interface BuyPageDocumentData {
  /**
   * Slice Zone field in *Buy Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: buy_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BuyPageDocumentDataSlicesSlice> /**
   * Meta Title field in *Buy Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: buy_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField

  /**
   * Meta Description field in *Buy Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: buy_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Buy Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: buy_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>
}

/**
 * Buy Page document from Prismic
 *
 * - **API ID**: `buy_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BuyPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<BuyPageDocumentData>,
    'buy_page',
    Lang
  >

/**
 * Content for Contact CTA documents
 */
interface ContactCtaDocumentData {
  /**
   * Title field in *Contact CTA*
   *
   * - **Field Type**: Text
   * - **Placeholder**: YOUR JOURNEY  STARTS HERE
   * - **API ID Path**: contact_cta.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Button Text field in *Contact CTA*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_cta.button_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField

  /**
   * Button URL field in *Contact CTA*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_cta.button_url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_url: prismic.LinkField
}

/**
 * Contact CTA document from Prismic
 *
 * - **API ID**: `contact_cta`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactCtaDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ContactCtaDocumentData>,
    'contact_cta',
    Lang
  >

type EcosystemPageDocumentDataSlicesSlice =
  | SectionIntroSlice
  | LogosSlice
  | HeroBannerSlice
  | FourColGridSlice

/**
 * Content for Ecosystem Page documents
 */
interface EcosystemPageDocumentData {
  /**
   * Slice Zone field in *Ecosystem Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: ecosystem_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<EcosystemPageDocumentDataSlicesSlice> /**
   * Meta Title field in *Ecosystem Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: ecosystem_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField

  /**
   * Meta Description field in *Ecosystem Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: ecosystem_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Ecosystem Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: ecosystem_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>
}

/**
 * Ecosystem Page document from Prismic
 *
 * - **API ID**: `ecosystem_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EcosystemPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<EcosystemPageDocumentData>,
    'ecosystem_page',
    Lang
  >

type ErrorPageDocumentDataSlicesSlice = PageBannerSlice

/**
 * Content for Error Page documents
 */
interface ErrorPageDocumentData {
  /**
   * Slice Zone field in *Error Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: error_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ErrorPageDocumentDataSlicesSlice> /**
   * Meta Title field in *Error Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: error_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField

  /**
   * Meta Description field in *Error Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: error_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Error Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: error_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>
}

/**
 * Error Page document from Prismic
 *
 * - **API ID**: `error_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ErrorPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ErrorPageDocumentData>,
    'error_page',
    Lang
  >

type HomepageDocumentDataSlicesSlice =
  | FaqsSlice
  | GamesFeedSlice
  | CarouselSlice
  | FeatureGridSlice
  | SectionIntroSlice
  | TwoColCtaSlice
  | TextSlice
  | LogosSlice
  | StatsSlice
  | HeroBannerSlice

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>

  /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField /**
   * Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.listing_title
   * - **Tab**: Listing Info
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  listing_title: prismic.KeyTextField

  /**
   * Description field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.listing_description
   * - **Tab**: Listing Info
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  listing_description: prismic.RichTextField

  /**
   * Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.listing_image
   * - **Tab**: Listing Info
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  listing_image: prismic.ImageField<never>
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    'homepage',
    Lang
  >

/**
 * Item in *Latest News → News Item*
 */
export interface LatestNewsDocumentDataNewsItemItem {
  /**
   * Image field in *Latest News → News Item*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: latest_news.news_item[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * Category field in *Latest News → News Item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: latest_news.news_item[].category
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  category: prismic.KeyTextField

  /**
   * Title field in *Latest News → News Item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: latest_news.news_item[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Author field in *Latest News → News Item*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: latest_news.news_item[].author
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  author: prismic.ContentRelationshipField<'author'>

  /**
   * Link field in *Latest News → News Item*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: latest_news.news_item[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField
}

/**
 * Content for Latest News documents
 */
interface LatestNewsDocumentData {
  /**
   * Title field in *Latest News*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: latest_news.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * News Item field in *Latest News*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: latest_news.news_item[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  news_item: prismic.GroupField<Simplify<LatestNewsDocumentDataNewsItemItem>>
}

/**
 * Latest News document from Prismic
 *
 * - **API ID**: `latest_news`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LatestNewsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<LatestNewsDocumentData>,
    'latest_news',
    Lang
  >

type LegalPageDocumentDataSlicesSlice = never

/**
 * Content for Legal Page documents
 */
interface LegalPageDocumentData {
  /**
   * Title field in *Legal Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: legal_page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Content field in *Legal Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: legal_page.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField

  /**
   * Slice Zone field in *Legal Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: legal_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<LegalPageDocumentDataSlicesSlice> /**
   * Meta Description field in *Legal Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: legal_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Legal Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: legal_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>

  /**
   * Meta Title field in *Legal Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: legal_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField /**
   * Title field in *Legal Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: legal_page.listing_title
   * - **Tab**: Listing Info
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  listing_title: prismic.KeyTextField

  /**
   * Description field in *Legal Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: legal_page.listing_description
   * - **Tab**: Listing Info
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  listing_description: prismic.RichTextField

  /**
   * Image field in *Legal Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: legal_page.listing_image
   * - **Tab**: Listing Info
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  listing_image: prismic.ImageField<never>
}

/**
 * Legal Page document from Prismic
 *
 * - **API ID**: `legal_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LegalPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<LegalPageDocumentData>,
    'legal_page',
    Lang
  >

/**
 * Content for Lottie Animation documents
 */
interface LottieAnimationDocumentData {
  /**
   * Name field in *Lottie Animation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: lottie_animation.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField

  /**
   * Animation JSON field in *Lottie Animation*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: lottie_animation.animation_json
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  animation_json: prismic.LinkToMediaField
}

/**
 * Lottie Animation document from Prismic
 *
 * - **API ID**: `lottie_animation`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LottieAnimationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<LottieAnimationDocumentData>,
    'lottie_animation',
    Lang
  >

type NavigationDocumentDataSlicesSlice = NavigationItemSlice

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
  /**
   * Slice Zone field in *Navigation*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<NavigationDocumentDataSlicesSlice>
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<NavigationDocumentData>,
    'navigation',
    Lang
  >

/**
 * Content for Schema - Organisation documents
 */
interface SchemaOrganisationDocumentData {
  /**
   * Company Name field in *Schema - Organisation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: schema_organisation.company_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  company_name: prismic.KeyTextField

  /**
   * Company Website field in *Schema - Organisation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: schema_organisation.company_website
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  company_website: prismic.KeyTextField

  /**
   * Contact Point - Email field in *Schema - Organisation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: schema_organisation.contact_point_email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  contact_point_email: prismic.KeyTextField

  /**
   * Contact Point - telephone field in *Schema - Organisation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: schema_organisation.contact_point_telephone
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  contact_point_telephone: prismic.KeyTextField

  /**
   * Address - Street field in *Schema - Organisation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: schema_organisation.address_street
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  address_street: prismic.KeyTextField

  /**
   * Address - Locality field in *Schema - Organisation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: schema_organisation.address_locality
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  address_locality: prismic.KeyTextField

  /**
   * Address - Region field in *Schema - Organisation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: schema_organisation.address_region
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  address_region: prismic.KeyTextField

  /**
   * Address - Postal Code field in *Schema - Organisation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: schema_organisation.address_postal_code
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  address_postal_code: prismic.KeyTextField

  /**
   * Address - Country field in *Schema - Organisation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: schema_organisation.address_country
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  address_country: prismic.KeyTextField
}

/**
 * Schema - Organisation document from Prismic
 *
 * - **API ID**: `schema_organisation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SchemaOrganisationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SchemaOrganisationDocumentData>,
    'schema_organisation',
    Lang
  >

/**
 * Content for Site Config documents
 */
interface SiteConfigDocumentData {
  /**
   * LinkedIn Profile URL field in *Site Config*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: site_config.linkedin_profile_url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkedin_profile_url: prismic.LinkField

  /**
   * Instagram Profile URL field in *Site Config*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: site_config.instagram_profile_url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  instagram_profile_url: prismic.LinkField

  /**
   * Facebook Profile URL field in *Site Config*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: site_config.facebook_profile_url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  facebook_profile_url: prismic.LinkField

  /**
   * Twitter Profile URL field in *Site Config*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: site_config.twitter_profile_url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  twitter_profile_url: prismic.LinkField

  /**
   * Discord Profile URL field in *Site Config*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: site_config.discord_profile_url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  discord_profile_url: prismic.LinkField

  /**
   * Reddit Profile URL field in *Site Config*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: site_config.reddit_profile_url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  reddit_profile_url: prismic.LinkField

  /**
   * YouTube Profile URL field in *Site Config*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: site_config.youtube_profile_url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  youtube_profile_url: prismic.LinkField
}

/**
 * Site Config document from Prismic
 *
 * - **API ID**: `site_config`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SiteConfigDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SiteConfigDocumentData>,
    'site_config',
    Lang
  >

export type AllDocumentTypes =
  | AuthorDocument
  | BuildPageDocument
  | BuyPageDocument
  | ContactCtaDocument
  | EcosystemPageDocument
  | ErrorPageDocument
  | HomepageDocument
  | LatestNewsDocument
  | LegalPageDocument
  | LottieAnimationDocument
  | NavigationDocument
  | SchemaOrganisationDocument
  | SiteConfigDocument

/**
 * Item in *Carousel → Default → Primary → Block*
 */
export interface CarouselSliceDefaultPrimaryBlockItem {
  /**
   * Image field in *Carousel → Default → Primary → Block*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.default.primary.block[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * Name field in *Carousel → Default → Primary → Block*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.default.primary.block[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField

  /**
   * Owner Handle field in *Carousel → Default → Primary → Block*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.default.primary.block[].owner_handle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  owner_handle: prismic.KeyTextField
}

/**
 * Primary content in *Carousel → Default → Primary*
 */
export interface CarouselSliceDefaultPrimary {
  /**
   * Block field in *Carousel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.default.primary.block[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  block: prismic.GroupField<Simplify<CarouselSliceDefaultPrimaryBlockItem>>
}

/**
 * Default variation for Carousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CarouselSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<CarouselSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *Carousel*
 */
type CarouselSliceVariation = CarouselSliceDefault

/**
 * Carousel Shared Slice
 *
 * - **API ID**: `carousel`
 * - **Description**: Carousel
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CarouselSlice = prismic.SharedSlice<
  'carousel',
  CarouselSliceVariation
>

/**
 * Primary content in *ContactInfo → Default → Primary*
 */
export interface ContactInfoSliceDefaultPrimary {
  /**
   * Title field in *ContactInfo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_info.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Content field in *ContactInfo → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_info.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField

  /**
   * Email field in *ContactInfo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_info.default.primary.email
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField
}

/**
 * Default variation for ContactInfo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactInfoSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ContactInfoSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *ContactInfo*
 */
type ContactInfoSliceVariation = ContactInfoSliceDefault

/**
 * ContactInfo Shared Slice
 *
 * - **API ID**: `contact_info`
 * - **Description**: ContactInfo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactInfoSlice = prismic.SharedSlice<
  'contact_info',
  ContactInfoSliceVariation
>

/**
 * Item in *Faqs → Default → Primary → FAQ*
 */
export interface FaqsSliceDefaultPrimaryFaqItem {
  /**
   * Question field in *Faqs → Default → Primary → FAQ*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.default.primary.faq[].question
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  question: prismic.KeyTextField

  /**
   * Answer field in *Faqs → Default → Primary → FAQ*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.default.primary.faq[].answer
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  answer: prismic.RichTextField
}

/**
 * Primary content in *Faqs → Default → Primary*
 */
export interface FaqsSliceDefaultPrimary {
  /**
   * Title field in *Faqs → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * FAQ field in *Faqs → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.default.primary.faq[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  faq: prismic.GroupField<Simplify<FaqsSliceDefaultPrimaryFaqItem>>
}

/**
 * Default variation for Faqs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqsSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<FaqsSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *Faqs*
 */
type FaqsSliceVariation = FaqsSliceDefault

/**
 * Faqs Shared Slice
 *
 * - **API ID**: `faqs`
 * - **Description**: Faqs
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqsSlice = prismic.SharedSlice<'faqs', FaqsSliceVariation>

/**
 * Item in *FeatureGrid → Default → Primary → Block*
 */
export interface FeatureGridSliceDefaultPrimaryBlockItem {
  /**
   * Title field in *FeatureGrid → Default → Primary → Block*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid.default.primary.block[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Text field in *FeatureGrid → Default → Primary → Block*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid.default.primary.block[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField

  /**
   * Button 1 Text field in *FeatureGrid → Default → Primary → Block*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid.default.primary.block[].button_1_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_1_text: prismic.KeyTextField

  /**
   * Button 1 URL field in *FeatureGrid → Default → Primary → Block*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid.default.primary.block[].button_1_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_1_url: prismic.LinkField

  /**
   * Button 2 Text field in *FeatureGrid → Default → Primary → Block*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid.default.primary.block[].button_2_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_2_text: prismic.KeyTextField

  /**
   * Button 2 URL field in *FeatureGrid → Default → Primary → Block*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid.default.primary.block[].button_2_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_2_url: prismic.LinkField

  /**
   * Width field in *FeatureGrid → Default → Primary → Block*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Full Width
   * - **API ID Path**: feature_grid.default.primary.block[].width
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  width: prismic.SelectField<
    'Full Width' | 'Half Width' | 'One Third' | 'Two Thirds',
    'filled'
  >

  /**
   * Lottie Animation field in *FeatureGrid → Default → Primary → Block*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid.default.primary.block[].lottie_animation
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  lottie_animation: prismic.ContentRelationshipField<'lottie_animation'>
}

/**
 * Primary content in *FeatureGrid → Default → Primary*
 */
export interface FeatureGridSliceDefaultPrimary {
  /**
   * Block field in *FeatureGrid → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid.default.primary.block[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  block: prismic.GroupField<Simplify<FeatureGridSliceDefaultPrimaryBlockItem>>
}

/**
 * Default variation for FeatureGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureGridSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<FeatureGridSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *FeatureGrid*
 */
type FeatureGridSliceVariation = FeatureGridSliceDefault

/**
 * FeatureGrid Shared Slice
 *
 * - **API ID**: `feature_grid`
 * - **Description**: FeatureGrid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureGridSlice = prismic.SharedSlice<
  'feature_grid',
  FeatureGridSliceVariation
>

/**
 * Item in *FourColGrid → Default → Primary → Block*
 */
export interface FourColGridSliceDefaultPrimaryBlockItem {
  /**
   * Image field in *FourColGrid → Default → Primary → Block*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: four_col_grid.default.primary.block[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * Title field in *FourColGrid → Default → Primary → Block*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: four_col_grid.default.primary.block[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Text field in *FourColGrid → Default → Primary → Block*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: four_col_grid.default.primary.block[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField

  /**
   * Button URL field in *FourColGrid → Default → Primary → Block*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: four_col_grid.default.primary.block[].button_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_url: prismic.LinkField
}

/**
 * Primary content in *FourColGrid → Default → Primary*
 */
export interface FourColGridSliceDefaultPrimary {
  /**
   * Button Text field in *FourColGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: four_col_grid.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField

  /**
   * Block field in *FourColGrid → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: four_col_grid.default.primary.block[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  block: prismic.GroupField<Simplify<FourColGridSliceDefaultPrimaryBlockItem>>
}

/**
 * Default variation for FourColGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FourColGridSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<FourColGridSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *FourColGrid*
 */
type FourColGridSliceVariation = FourColGridSliceDefault

/**
 * FourColGrid Shared Slice
 *
 * - **API ID**: `four_col_grid`
 * - **Description**: FourColGrid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FourColGridSlice = prismic.SharedSlice<
  'four_col_grid',
  FourColGridSliceVariation
>

/**
 * Item in *GamesFeed → Default → Primary → Block*
 */
export interface GamesFeedSliceDefaultPrimaryBlockItem {
  /**
   * Image field in *GamesFeed → Default → Primary → Block*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: games_feed.default.primary.block[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * Type field in *GamesFeed → Default → Primary → Block*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: games_feed.default.primary.block[].type
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  type: prismic.KeyTextField

  /**
   * URL field in *GamesFeed → Default → Primary → Block*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: games_feed.default.primary.block[].url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.LinkField
}

/**
 * Primary content in *GamesFeed → Default → Primary*
 */
export interface GamesFeedSliceDefaultPrimary {
  /**
   * Title field in *GamesFeed → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: games_feed.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Text field in *GamesFeed → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: games_feed.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField

  /**
   * Button 1 Text field in *GamesFeed → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: games_feed.default.primary.button_1_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_1_text: prismic.KeyTextField

  /**
   * Button 1 URL field in *GamesFeed → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: games_feed.default.primary.button_1_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_1_url: prismic.LinkField

  /**
   * Theme field in *GamesFeed → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Light
   * - **API ID Path**: games_feed.default.primary.theme
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  theme: prismic.SelectField<'Light' | 'Dark', 'filled'>

  /**
   * Game Block Button Text field in *GamesFeed → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Learn more
   * - **API ID Path**: games_feed.default.primary.game_block_button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  game_block_button_text: prismic.KeyTextField

  /**
   * Block field in *GamesFeed → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: games_feed.default.primary.block[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  block: prismic.GroupField<Simplify<GamesFeedSliceDefaultPrimaryBlockItem>>
}

/**
 * Default variation for GamesFeed Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GamesFeedSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<GamesFeedSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *GamesFeed*
 */
type GamesFeedSliceVariation = GamesFeedSliceDefault

/**
 * GamesFeed Shared Slice
 *
 * - **API ID**: `games_feed`
 * - **Description**: GamesFeed
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GamesFeedSlice = prismic.SharedSlice<
  'games_feed',
  GamesFeedSliceVariation
>

/**
 * Item in *HeroBanner → Default → Primary → Block*
 */
export interface HeroBannerSliceDefaultPrimaryBlockItem {
  /**
   * Image field in *HeroBanner → Default → Primary → Block*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.default.primary.block[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * Type field in *HeroBanner → Default → Primary → Block*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.default.primary.block[].type
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  type: prismic.KeyTextField

  /**
   * URL field in *HeroBanner → Default → Primary → Block*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.default.primary.block[].url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.LinkField
}

/**
 * Primary content in *HeroBanner → Default → Primary*
 */
export interface HeroBannerSliceDefaultPrimary {
  /**
   * Title field in *HeroBanner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Building the future of gaming
   * - **API ID Path**: hero_banner.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Text field in *HeroBanner → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField

  /**
   * Button 1 Text field in *HeroBanner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.default.primary.button_1_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_1_text: prismic.KeyTextField

  /**
   * Button 1 URL field in *HeroBanner → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.default.primary.button_1_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_1_url: prismic.LinkField

  /**
   * Button 2 Text field in *HeroBanner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.default.primary.button_2_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_2_text: prismic.KeyTextField

  /**
   * Button 2 URL field in *HeroBanner → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.default.primary.button_2_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_2_url: prismic.LinkField

  /**
   * Animation Direction field in *HeroBanner → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Vertical
   * - **API ID Path**: hero_banner.default.primary.animation_direction
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  animation_direction: prismic.SelectField<'Vertical' | 'Horizontal', 'filled'>

  /**
   * Theme field in *HeroBanner → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Light
   * - **API ID Path**: hero_banner.default.primary.theme
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  theme: prismic.SelectField<'Light' | 'Dark', 'filled'>

  /**
   * Block field in *HeroBanner → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.default.primary.block[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  block: prismic.GroupField<Simplify<HeroBannerSliceDefaultPrimaryBlockItem>>
}

/**
 * Default variation for HeroBanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroBannerSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<HeroBannerSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *HeroBanner*
 */
type HeroBannerSliceVariation = HeroBannerSliceDefault

/**
 * HeroBanner Shared Slice
 *
 * - **API ID**: `hero_banner`
 * - **Description**: HeroBanner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroBannerSlice = prismic.SharedSlice<
  'hero_banner',
  HeroBannerSliceVariation
>

/**
 * Primary content in *ParallaxImage → Default → Primary*
 */
export interface ImageSliceDefaultPrimary {
  /**
   * Image field in *ParallaxImage → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>
}

/**
 * Default variation for ParallaxImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ImageSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *ParallaxImage*
 */
type ImageSliceVariation = ImageSliceDefault

/**
 * ParallaxImage Shared Slice
 *
 * - **API ID**: `image`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSlice = prismic.SharedSlice<'image', ImageSliceVariation>

/**
 * Primary content in *ImageWithCaption → Default → Primary*
 */
export interface ImageWithCaptionSliceDefaultPrimary {
  /**
   * Image field in *ImageWithCaption → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_caption.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * Caption field in *ImageWithCaption → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_caption.default.primary.caption
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  caption: prismic.KeyTextField

  /**
   * Width field in *ImageWithCaption → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Edge to Edge
   * - **API ID Path**: image_with_caption.default.primary.width
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  width: prismic.SelectField<
    'Edge to Edge' | 'Full Column Width' | 'Inset (70% Column Width)',
    'filled'
  >
}

/**
 * Default variation for ImageWithCaption Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageWithCaptionSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ImageWithCaptionSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *ImageWithCaption*
 */
type ImageWithCaptionSliceVariation = ImageWithCaptionSliceDefault

/**
 * ImageWithCaption Shared Slice
 *
 * - **API ID**: `image_with_caption`
 * - **Description**: ImageWithCaption
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageWithCaptionSlice = prismic.SharedSlice<
  'image_with_caption',
  ImageWithCaptionSliceVariation
>

/**
 * Item in *Logos → Default → Primary → Logo*
 */
export interface LogosSliceDefaultPrimaryLogosItem {
  /**
   * Image field in *Logos → Default → Primary → Logo*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: logos.default.primary.logos[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>
}

/**
 * Primary content in *Logos → Default → Primary*
 */
export interface LogosSliceDefaultPrimary {
  /**
   * Title field in *Logos → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: logos.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Title Position field in *Logos → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Center
   * - **API ID Path**: logos.default.primary.title_position
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  title_position: prismic.SelectField<'Center' | 'Left', 'filled'>

  /**
   * Theme field in *Logos → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Light
   * - **API ID Path**: logos.default.primary.theme
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  theme: prismic.SelectField<'Light' | 'Dark', 'filled'>

  /**
   * Logo field in *Logos → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: logos.default.primary.logos[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  logos: prismic.GroupField<Simplify<LogosSliceDefaultPrimaryLogosItem>>
}

/**
 * Default variation for Logos Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LogosSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<LogosSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *Logos*
 */
type LogosSliceVariation = LogosSliceDefault

/**
 * Logos Shared Slice
 *
 * - **API ID**: `logos`
 * - **Description**: Logos
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LogosSlice = prismic.SharedSlice<'logos', LogosSliceVariation>

/**
 * Item in *MeetTheTeam → Default → Primary → Employee*
 */
export interface MeetTheTeamSliceDefaultPrimaryEmployeeItem {
  /**
   * Name field in *MeetTheTeam → Default → Primary → Employee*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: meet_the_team.default.primary.employee[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField

  /**
   * Role field in *MeetTheTeam → Default → Primary → Employee*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: meet_the_team.default.primary.employee[].role
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  role: prismic.KeyTextField

  /**
   * Image field in *MeetTheTeam → Default → Primary → Employee*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: meet_the_team.default.primary.employee[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>
}

/**
 * Primary content in *MeetTheTeam → Default → Primary*
 */
export interface MeetTheTeamSliceDefaultPrimary {
  /**
   * Title field in *MeetTheTeam → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: meet_the_team.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Text field in *MeetTheTeam → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: meet_the_team.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField

  /**
   * Employee field in *MeetTheTeam → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: meet_the_team.default.primary.employee[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  employee: prismic.GroupField<
    Simplify<MeetTheTeamSliceDefaultPrimaryEmployeeItem>
  >
}

/**
 * Default variation for MeetTheTeam Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MeetTheTeamSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<MeetTheTeamSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *MeetTheTeam*
 */
type MeetTheTeamSliceVariation = MeetTheTeamSliceDefault

/**
 * MeetTheTeam Shared Slice
 *
 * - **API ID**: `meet_the_team`
 * - **Description**: MeetTheTeam
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MeetTheTeamSlice = prismic.SharedSlice<
  'meet_the_team',
  MeetTheTeamSliceVariation
>

/**
 * Primary content in *NavigationItem → Default → Primary*
 */
export interface NavigationItemSliceDefaultPrimary {
  /**
   * Label field in *NavigationItem → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_item.default.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField

  /**
   * Link field in *NavigationItem → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_item.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField
}

/**
 * Primary content in *NavigationItem → Items*
 */
export interface NavigationItemSliceDefaultItem {
  /**
   * Child Label field in *NavigationItem → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_item.items[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField

  /**
   * Child Link field in *NavigationItem → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_item.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField
}

/**
 * Default variation for NavigationItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationItemSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<NavigationItemSliceDefaultPrimary>,
  Simplify<NavigationItemSliceDefaultItem>
>

/**
 * Slice variation for *NavigationItem*
 */
type NavigationItemSliceVariation = NavigationItemSliceDefault

/**
 * NavigationItem Shared Slice
 *
 * - **API ID**: `navigation_item`
 * - **Description**: NavigationItem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationItemSlice = prismic.SharedSlice<
  'navigation_item',
  NavigationItemSliceVariation
>

/**
 * Primary content in *PageBanner → Default → Primary*
 */
export interface PageBannerSliceDefaultPrimary {
  /**
   * Title field in *PageBanner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_banner.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Text field in *PageBanner → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_banner.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField

  /**
   * Button 1 Text field in *PageBanner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_banner.default.primary.button_1_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_1_text: prismic.KeyTextField

  /**
   * Button 1 URL field in *PageBanner → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: page_banner.default.primary.button_1_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_1_url: prismic.LinkField

  /**
   * Button 2 Text field in *PageBanner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_banner.default.primary.button_2_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_2_text: prismic.KeyTextField

  /**
   * Button 2 URL field in *PageBanner → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: page_banner.default.primary.button_2_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_2_url: prismic.LinkField

  /**
   * Image field in *PageBanner → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page_banner.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>
}

/**
 * Default variation for PageBanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PageBannerSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<PageBannerSliceDefaultPrimary>,
  never
>

/**
 * Primary content in *PageBanner → Image Left → Primary*
 */
export interface PageBannerSliceImageLeftPrimary {
  /**
   * Title field in *PageBanner → Image Left → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_banner.imageLeft.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Text field in *PageBanner → Image Left → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_banner.imageLeft.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField

  /**
   * Button 1 Text field in *PageBanner → Image Left → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_banner.imageLeft.primary.button_1_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_1_text: prismic.KeyTextField

  /**
   * Button 1 URL field in *PageBanner → Image Left → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: page_banner.imageLeft.primary.button_1_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_1_url: prismic.LinkField

  /**
   * Button 2 Text field in *PageBanner → Image Left → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_banner.imageLeft.primary.button_2_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_2_text: prismic.KeyTextField

  /**
   * Button 2 URL field in *PageBanner → Image Left → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: page_banner.imageLeft.primary.button_2_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_2_url: prismic.LinkField

  /**
   * Image field in *PageBanner → Image Left → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page_banner.imageLeft.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>
}

/**
 * Image Left variation for PageBanner Slice
 *
 * - **API ID**: `imageLeft`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PageBannerSliceImageLeft = prismic.SharedSliceVariation<
  'imageLeft',
  Simplify<PageBannerSliceImageLeftPrimary>,
  never
>

/**
 * Slice variation for *PageBanner*
 */
type PageBannerSliceVariation =
  | PageBannerSliceDefault
  | PageBannerSliceImageLeft

/**
 * PageBanner Shared Slice
 *
 * - **API ID**: `page_banner`
 * - **Description**: PageBanner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PageBannerSlice = prismic.SharedSlice<
  'page_banner',
  PageBannerSliceVariation
>

/**
 * Primary content in *SectionIntro → Default → Primary*
 */
export interface SectionIntroSliceDefaultPrimary {
  /**
   * Title field in *SectionIntro → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_intro.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Text field in *SectionIntro → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_intro.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField

  /**
   * Button Text field in *SectionIntro → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_intro.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField

  /**
   * Button URL field in *SectionIntro → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: section_intro.default.primary.button_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_url: prismic.LinkField

  /**
   * Link Text field in *SectionIntro → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_intro.default.primary.link_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_text: prismic.KeyTextField

  /**
   * Link URL field in *SectionIntro → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: section_intro.default.primary.link_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_url: prismic.LinkField
}

/**
 * Default variation for SectionIntro Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionIntroSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<SectionIntroSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *SectionIntro*
 */
type SectionIntroSliceVariation = SectionIntroSliceDefault

/**
 * SectionIntro Shared Slice
 *
 * - **API ID**: `section_intro`
 * - **Description**: SectionIntro
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionIntroSlice = prismic.SharedSlice<
  'section_intro',
  SectionIntroSliceVariation
>

/**
 * Item in *Stats → Default → Primary → Stat*
 */
export interface StatsSliceDefaultPrimaryStatsItem {
  /**
   * Title field in *Stats → Default → Primary → Stat*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: stats.default.primary.stats[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Text field in *Stats → Default → Primary → Stat*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: stats.default.primary.stats[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField
}

/**
 * Primary content in *Stats → Default → Primary*
 */
export interface StatsSliceDefaultPrimary {
  /**
   * Link Text field in *Stats → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: stats.default.primary.link_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_text: prismic.KeyTextField

  /**
   * URL field in *Stats → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: stats.default.primary.url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.LinkField

  /**
   * Stat field in *Stats → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: stats.default.primary.stats[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  stats: prismic.GroupField<Simplify<StatsSliceDefaultPrimaryStatsItem>>
}

/**
 * Default variation for Stats Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StatsSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<StatsSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *Stats*
 */
type StatsSliceVariation = StatsSliceDefault

/**
 * Stats Shared Slice
 *
 * - **API ID**: `stats`
 * - **Description**: Stats
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StatsSlice = prismic.SharedSlice<'stats', StatsSliceVariation>

/**
 * Item in *Testimonials → Default → Primary → Testimonial*
 */
export interface TestimonialsSliceDefaultPrimaryTestimonialItem {
  /**
   * Quote field in *Testimonials → Default → Primary → Testimonial*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonial[].quote
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  quote: prismic.RichTextField

  /**
   * Author field in *Testimonials → Default → Primary → Testimonial*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonial[].author
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author: prismic.KeyTextField

  /**
   * Role / Company field in *Testimonials → Default → Primary → Testimonial*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonial[].company
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  company: prismic.KeyTextField

  /**
   * Image field in *Testimonials → Default → Primary → Testimonial*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonial[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>
}

/**
 * Primary content in *Testimonials → Default → Primary*
 */
export interface TestimonialsSliceDefaultPrimary {
  /**
   * Title field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Testimonial field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonial[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  testimonial: prismic.GroupField<
    Simplify<TestimonialsSliceDefaultPrimaryTestimonialItem>
  >
}

/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<TestimonialsSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *Testimonials*
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault

/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: Testimonials
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSlice = prismic.SharedSlice<
  'testimonials',
  TestimonialsSliceVariation
>

/**
 * Primary content in *Text → Default → Primary*
 */
export interface TextSliceDefaultPrimary {
  /**
   * Text field in *Text → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField
}

/**
 * Default variation for Text Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<TextSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *Text*
 */
type TextSliceVariation = TextSliceDefault

/**
 * Text Shared Slice
 *
 * - **API ID**: `text`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSlice = prismic.SharedSlice<'text', TextSliceVariation>

/**
 * Primary content in *Tip → Default → Primary*
 */
export interface TipSliceDefaultPrimary {
  /**
   * Text field in *Tip → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tip.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField
}

/**
 * Default variation for Tip Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TipSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<TipSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *Tip*
 */
type TipSliceVariation = TipSliceDefault

/**
 * Tip Shared Slice
 *
 * - **API ID**: `tip`
 * - **Description**: Tip
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TipSlice = prismic.SharedSlice<'tip', TipSliceVariation>

/**
 * Primary content in *TwoColCta → Default → Primary*
 */
export interface TwoColCtaSliceDefaultPrimary {
  /**
   * Title field in *TwoColCta → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_col_cta.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Text field in *TwoColCta → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_col_cta.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField

  /**
   * Button Text field in *TwoColCta → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_col_cta.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField

  /**
   * Button URL field in *TwoColCta → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: two_col_cta.default.primary.button_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_url: prismic.LinkField

  /**
   * Image field in *TwoColCta → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: two_col_cta.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * Video field in *TwoColCta → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: two_col_cta.default.primary.video
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video: prismic.LinkField
}

/**
 * Default variation for TwoColCta Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TwoColCtaSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<TwoColCtaSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *TwoColCta*
 */
type TwoColCtaSliceVariation = TwoColCtaSliceDefault

/**
 * TwoColCta Shared Slice
 *
 * - **API ID**: `two_col_cta`
 * - **Description**: TwoColCta
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TwoColCtaSlice = prismic.SharedSlice<
  'two_col_cta',
  TwoColCtaSliceVariation
>

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>
  }

  namespace Content {
    export type {
      AuthorDocument,
      AuthorDocumentData,
      BuildPageDocument,
      BuildPageDocumentData,
      BuildPageDocumentDataSlicesSlice,
      BuyPageDocument,
      BuyPageDocumentData,
      BuyPageDocumentDataSlicesSlice,
      ContactCtaDocument,
      ContactCtaDocumentData,
      EcosystemPageDocument,
      EcosystemPageDocumentData,
      EcosystemPageDocumentDataSlicesSlice,
      ErrorPageDocument,
      ErrorPageDocumentData,
      ErrorPageDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      LatestNewsDocument,
      LatestNewsDocumentData,
      LatestNewsDocumentDataNewsItemItem,
      LegalPageDocument,
      LegalPageDocumentData,
      LegalPageDocumentDataSlicesSlice,
      LottieAnimationDocument,
      LottieAnimationDocumentData,
      NavigationDocument,
      NavigationDocumentData,
      NavigationDocumentDataSlicesSlice,
      SchemaOrganisationDocument,
      SchemaOrganisationDocumentData,
      SiteConfigDocument,
      SiteConfigDocumentData,
      AllDocumentTypes,
      CarouselSlice,
      CarouselSliceDefaultPrimaryBlockItem,
      CarouselSliceDefaultPrimary,
      CarouselSliceVariation,
      CarouselSliceDefault,
      ContactInfoSlice,
      ContactInfoSliceDefaultPrimary,
      ContactInfoSliceVariation,
      ContactInfoSliceDefault,
      FaqsSlice,
      FaqsSliceDefaultPrimaryFaqItem,
      FaqsSliceDefaultPrimary,
      FaqsSliceVariation,
      FaqsSliceDefault,
      FeatureGridSlice,
      FeatureGridSliceDefaultPrimaryBlockItem,
      FeatureGridSliceDefaultPrimary,
      FeatureGridSliceVariation,
      FeatureGridSliceDefault,
      FourColGridSlice,
      FourColGridSliceDefaultPrimaryBlockItem,
      FourColGridSliceDefaultPrimary,
      FourColGridSliceVariation,
      FourColGridSliceDefault,
      GamesFeedSlice,
      GamesFeedSliceDefaultPrimaryBlockItem,
      GamesFeedSliceDefaultPrimary,
      GamesFeedSliceVariation,
      GamesFeedSliceDefault,
      HeroBannerSlice,
      HeroBannerSliceDefaultPrimaryBlockItem,
      HeroBannerSliceDefaultPrimary,
      HeroBannerSliceVariation,
      HeroBannerSliceDefault,
      ImageSlice,
      ImageSliceDefaultPrimary,
      ImageSliceVariation,
      ImageSliceDefault,
      ImageWithCaptionSlice,
      ImageWithCaptionSliceDefaultPrimary,
      ImageWithCaptionSliceVariation,
      ImageWithCaptionSliceDefault,
      LogosSlice,
      LogosSliceDefaultPrimaryLogosItem,
      LogosSliceDefaultPrimary,
      LogosSliceVariation,
      LogosSliceDefault,
      MeetTheTeamSlice,
      MeetTheTeamSliceDefaultPrimaryEmployeeItem,
      MeetTheTeamSliceDefaultPrimary,
      MeetTheTeamSliceVariation,
      MeetTheTeamSliceDefault,
      NavigationItemSlice,
      NavigationItemSliceDefaultPrimary,
      NavigationItemSliceDefaultItem,
      NavigationItemSliceVariation,
      NavigationItemSliceDefault,
      PageBannerSlice,
      PageBannerSliceDefaultPrimary,
      PageBannerSliceImageLeftPrimary,
      PageBannerSliceVariation,
      PageBannerSliceDefault,
      PageBannerSliceImageLeft,
      SectionIntroSlice,
      SectionIntroSliceDefaultPrimary,
      SectionIntroSliceVariation,
      SectionIntroSliceDefault,
      StatsSlice,
      StatsSliceDefaultPrimaryStatsItem,
      StatsSliceDefaultPrimary,
      StatsSliceVariation,
      StatsSliceDefault,
      TestimonialsSlice,
      TestimonialsSliceDefaultPrimaryTestimonialItem,
      TestimonialsSliceDefaultPrimary,
      TestimonialsSliceVariation,
      TestimonialsSliceDefault,
      TextSlice,
      TextSliceDefaultPrimary,
      TextSliceVariation,
      TextSliceDefault,
      TipSlice,
      TipSliceDefaultPrimary,
      TipSliceVariation,
      TipSliceDefault,
      TwoColCtaSlice,
      TwoColCtaSliceDefaultPrimary,
      TwoColCtaSliceVariation,
      TwoColCtaSliceDefault,
    }
  }
}
