import type { Metadata } from 'next'
import '@/stylesheets/style.sass'
import Navigation from "@/components/navigation";
import {CookieBanner} from "@superrb/react-addons/components";
import Scripts from "@/components/scripts";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <Navigation name={'navigation'}/>
      {children}
      <CookieBanner />
      <Scripts />
      </body>
    </html>
  )
}
