// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic'

export const components = {
  contact_info: dynamic(() => import('./ContactInfo')),
  navigation_item: dynamic(() => import('./NavigationItem')),
}
